### ISSUE TITLE
Build a new docker image

### ISSUE THREAD

**Issue by tsawada** [Olivr/copybara-action#71]
Hi! Thanks for working on this project.
Recently there's a critical bugfix in Copybara upstream and it'd be great if `olivr/copybara` image picks it up. It seems the image building action has been paused due to lack of activity.
https://github.com/Olivr/copybara-action/actions/workflows/copybara-docker.yml

Could you manually roll out a new docker build?
Thanks in advance!

**Comment by politician** [comment]
@tsawada thanks for noticing! I have just restarted the workflow and the latest image has just been rebuilt.
